/datum/voicepack/male/tabaxi/get_sound(soundin, modifiers)
	var/used
	switch(modifiers)
		if("old")
			used = getmold(soundin)
		if("young")
			used = getmyoung(soundin)
		if("silenced")
			used = getmsilenced(soundin)
	if(!used)
		switch(soundin)
			if("meow")
				used = list('sound/vo/male/tabaxi/tabaxi_meow1.ogg', 'sound/vo/male/tabaxi/tabaxi_meow2.ogg')
			if("purr")
				used = list('sound/vo/male/tabaxi/tabaxi_purr.ogg')
			if("trill")
				used = list('sound/vo/male/tabaxi/tabaxi_mrrp1.ogg', 'sound/vo/male/tabaxi/tabaxi_mrrp2.ogg')
			if("hiss")
				used = list('sound/vo/male/tabaxi/tabaxi_hiss1.ogg', 'sound/vo/male/tabaxi/tabaxi_hiss2.ogg')
			else
				return ..()
	return used 
